<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <!-- xunit.v3 test projects are executables. -->
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/WaylandSharpest/WaylandSharpest.csproj" />
    <ProjectReference Include="../../src/WaylandSharpest.Generator/WaylandSharpest.Generator.csproj"
                      ReferenceOutputAssembly="false"
                      OutputItemType="Analyzer" />
    <AdditionalFiles Include="protocols/test-helpers.xml"
                     WaylandNamespace="WaylandSharpest.Tests.Protocol" />
  </ItemGroup>

  <ItemGroup>
    <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="WaylandNamespace" />
  </ItemGroup>

</Project>
