// <auto-generated>
// Generated by WaylandSharpest.Generator from protocol 'sample'.
// </auto-generated>
#nullable enable

namespace WaylandProtocols
{
    /// <summary>a sample interface for snapshot testing (client proxy for 'sample_thing').</summary>
    [global::Wayland.WaylandProxy("sample_thing")]
    public sealed partial class SampleThing : global::Wayland.WlProxy, global::Wayland.IWaylandObject<SampleThing>
    {
        /// <summary>Interface metadata for 'sample_thing' version 3.</summary>
        public static global::Wayland.WlInterfaceSpec Interface { get; } = new global::Wayland.WlInterfaceSpec(
            "sample_thing",
            3,
            new global::Wayland.WlMessageSpec[]
            {
                new global::Wayland.WlMessageSpec("set_mode", "u", new global::System.Func<global::Wayland.WlInterfaceSpec>?[] { null }),
                new global::Wayland.WlMessageSpec("make_child", "n?s", new global::System.Func<global::Wayland.WlInterfaceSpec>?[] { static () => global::WaylandProtocols.SampleChild.Interface!, null }),
                new global::Wayland.WlMessageSpec("give_data", "ah", new global::System.Func<global::Wayland.WlInterfaceSpec>?[] { null, null }),
                new global::Wayland.WlMessageSpec("convert", "n", new global::System.Func<global::Wayland.WlInterfaceSpec>?[] { static () => global::WaylandProtocols.SampleChild.Interface! }),
                new global::Wayland.WlMessageSpec("destroy", "", null),
            },
            new global::Wayland.WlMessageSpec[]
            {
                new global::Wayland.WlMessageSpec("state", "uf?o", new global::System.Func<global::Wayland.WlInterfaceSpec>?[] { null, null, static () => global::WaylandProtocols.SampleChild.Interface! }),
                new global::Wayland.WlMessageSpec("spawned", "2n", new global::System.Func<global::Wayland.WlInterfaceSpec>?[] { static () => global::WaylandProtocols.SampleChild.Interface! }),
            },
            static (handle, display) => new SampleThing(handle, display));

        internal SampleThing(nint handle, global::Wayland.WlDisplay display) : base(handle, display)
        {
        }

        protected override global::Wayland.WlInterfaceSpec Spec => Interface;

        public enum Mode : int
        {
            /// <summary>slow mode</summary>
            Slow = 0,
            /// <summary>fast mode</summary>
            Fast = 1,
        }

        [global::System.Flags]
        public enum Flags : uint
        {
            A = 1u,
            B = 2u,
        }

        /// <summary>Sends the 'set_mode' request.</summary>
        public void SetMode(global::WaylandProtocols.SampleThing.Mode mode)
        {
            global::System.Span<global::Wayland.WlArg> _args = stackalloc global::Wayland.WlArg[1];
            _args[0].U = (uint)mode;
            MarshalRequest(0u, _args);
        }

        /// <summary>Sends the 'make_child' request.</summary>
        public global::WaylandProtocols.SampleChild MakeChild(string? label)
        {
            global::System.Span<global::Wayland.WlArg> _args = stackalloc global::Wayland.WlArg[2];
            nint _s1 = AllocString(label);
            try
            {
                _args[1].Ptr = _s1;
                return (global::WaylandProtocols.SampleChild)MarshalConstructor(1u, _args, global::WaylandProtocols.SampleChild.Interface);
            }
            finally
            {
                FreeString(_s1);
            }
        }

        /// <summary>Sends the 'give_data' request.</summary>
        public void GiveData(global::System.ReadOnlySpan<byte> data, int fd)
        {
            global::System.Span<global::Wayland.WlArg> _args = stackalloc global::Wayland.WlArg[2];
            var _a0 = AllocArray(data);
            try
            {
                _args[0].Ptr = _a0.Pointer;
                _args[1].Fd = fd;
                MarshalRequest(2u, _args);
            }
            finally
            {
                _a0.Dispose();
            }
        }

        /// <summary>Sends the 'convert' request.</summary>
        public global::WaylandProtocols.SampleChild Convert()
        {
            global::System.Span<global::Wayland.WlArg> _args = stackalloc global::Wayland.WlArg[1];
            return (global::WaylandProtocols.SampleChild)MarshalDestructorConstructor(3u, _args, global::WaylandProtocols.SampleChild.Interface);
        }

        /// <summary>Sends the 'destroy' request.</summary>
        public void Destroy()
        {
            MarshalDestructor(4u, default);
        }

        /// <summary>Routes disposal through the 'destroy' destructor request.</summary>
        protected override void DisposeCore() => Destroy();

        /// <summary>Arguments of the 'state' event.</summary>
        public readonly struct StateEventArgs
        {
            internal StateEventArgs(uint serial, global::Wayland.WlFixed position, global::WaylandProtocols.SampleChild? child, nint childHandle)
            {
                Serial = serial;
                Position = position;
                Child = child;
                ChildHandle = childHandle;
            }

            public uint Serial { get; }
            public global::Wayland.WlFixed Position { get; }
            public global::WaylandProtocols.SampleChild? Child { get; }
            /// <summary>Raw wl_proxy pointer of 'child'; valid even when the proxy is owned by another library.</summary>
            public nint ChildHandle { get; }
        }

        /// <summary>Raised for the 'state' event.</summary>
        public event global::System.EventHandler<StateEventArgs>? State;

        /// <summary>Arguments of the 'spawned' event.</summary>
        public readonly struct SpawnedEventArgs
        {
            internal SpawnedEventArgs(global::WaylandProtocols.SampleChild child)
            {
                Child = child;
            }

            public global::WaylandProtocols.SampleChild Child { get; }
        }

        /// <summary>Raised for the 'spawned' event. Available since version 2.</summary>
        public event global::System.EventHandler<SpawnedEventArgs>? Spawned;

        protected override void HandleEvent(uint opcode, global::System.ReadOnlySpan<global::Wayland.WlArg> args)
        {
            switch (opcode)
            {
                case 0u:
                    State?.Invoke(this, new StateEventArgs(args[0].U, args[1].F, GetProxy<global::WaylandProtocols.SampleChild>(args[2]), GetProxyHandle(args[2])));
                    break;
                case 1u:
                    Spawned?.Invoke(this, new SpawnedEventArgs((global::WaylandProtocols.SampleChild)WrapNewProxy(args[0], global::WaylandProtocols.SampleChild.Interface)));
                    break;
            }
        }
    }

    /// <summary>a sample interface for snapshot testing (server resource for 'sample_thing').</summary>
    [global::Wayland.WaylandResource("sample_thing")]
    public sealed partial class SampleThingResource : global::Wayland.Server.WlResource
    {
        /// <summary>Creates the resource for a bound global or a client-requested object id.</summary>
        public SampleThingResource(global::Wayland.Server.WlClient client, uint version, uint id) : base(client, SampleThing.Interface, version, id)
        {
        }

        protected override global::Wayland.WlInterfaceSpec Spec => SampleThing.Interface;

        /// <summary>Arguments of the 'set_mode' event.</summary>
        public readonly struct SetModeEventArgs
        {
            internal SetModeEventArgs(global::WaylandProtocols.SampleThing.Mode mode)
            {
                Mode = mode;
            }

            public global::WaylandProtocols.SampleThing.Mode Mode { get; }
        }

        /// <summary>Raised when the client sends the 'set_mode' request.</summary>
        public event global::System.EventHandler<SetModeEventArgs>? SetMode;

        /// <summary>Arguments of the 'make_child' event.</summary>
        public readonly struct MakeChildEventArgs
        {
            internal MakeChildEventArgs(uint id, string? label)
            {
                Id = id;
                Label = label;
            }

            /// <summary>New object id; construct the matching resource with it.</summary>
            public uint Id { get; }
            public string? Label { get; }
        }

        /// <summary>Raised when the client sends the 'make_child' request.</summary>
        public event global::System.EventHandler<MakeChildEventArgs>? MakeChild;

        /// <summary>Arguments of the 'give_data' event.</summary>
        public readonly struct GiveDataEventArgs
        {
            internal GiveDataEventArgs(byte[] data, int fd)
            {
                Data = data;
                Fd = fd;
            }

            public byte[] Data { get; }
            public int Fd { get; }
        }

        /// <summary>Raised when the client sends the 'give_data' request.</summary>
        public event global::System.EventHandler<GiveDataEventArgs>? GiveData;

        /// <summary>Arguments of the 'convert' event.</summary>
        public readonly struct ConvertEventArgs
        {
            internal ConvertEventArgs(uint id)
            {
                Id = id;
            }

            /// <summary>New object id; construct the matching resource with it.</summary>
            public uint Id { get; }
        }

        /// <summary>Raised when the client sends the 'convert' request. The resource is destroyed automatically after this event.</summary>
        public event global::System.EventHandler<ConvertEventArgs>? Convert;

        /// <summary>Arguments of the 'destroy' event.</summary>
        public readonly struct DestroyRequestEventArgs
        {
        }

        /// <summary>Raised when the client sends the 'destroy' request. The resource is destroyed automatically after this event.</summary>
        public event global::System.EventHandler<DestroyRequestEventArgs>? DestroyRequest;

        /// <summary>Sends the 'state' event to the client.</summary>
        public void SendState(uint serial, global::Wayland.WlFixed position, global::WaylandProtocols.SampleChildResource? child)
        {
            global::System.Span<global::Wayland.WlArg> _args = stackalloc global::Wayland.WlArg[3];
            _args[0].U = serial;
            _args[1].F = position;
            _args[2].Ptr = child is null ? 0 : child.RawHandle;
            PostEvent(0u, _args);
        }

        /// <summary>Sends the 'spawned' event to the client. Available since version 2.</summary>
        public void SendSpawned(global::WaylandProtocols.SampleChildResource child)
        {
            global::System.Span<global::Wayland.WlArg> _args = stackalloc global::Wayland.WlArg[1];
            _args[0].Ptr = child.RawHandle;
            PostEvent(1u, _args);
        }

        protected override void HandleRequest(uint opcode, global::System.ReadOnlySpan<global::Wayland.WlArg> args)
        {
            switch (opcode)
            {
                case 0u:
                    SetMode?.Invoke(this, new SetModeEventArgs((global::WaylandProtocols.SampleThing.Mode)args[0].U));
                    break;
                case 1u:
                    MakeChild?.Invoke(this, new MakeChildEventArgs(args[0].U, GetString(args[1])));
                    break;
                case 2u:
                    GiveData?.Invoke(this, new GiveDataEventArgs(GetArray(args[0]), args[1].Fd));
                    break;
                case 3u:
                    Convert?.Invoke(this, new ConvertEventArgs(args[0].U));
                    CompleteDestructorRequest();
                    break;
                case 4u:
                    DestroyRequest?.Invoke(this, new DestroyRequestEventArgs());
                    CompleteDestructorRequest();
                    break;
            }
        }
    }

    /// <summary>Client proxy for the 'sample_child' interface.</summary>
    [global::Wayland.WaylandProxy("sample_child")]
    public sealed partial class SampleChild : global::Wayland.WlProxy, global::Wayland.IWaylandObject<SampleChild>
    {
        /// <summary>Interface metadata for 'sample_child' version 1.</summary>
        public static global::Wayland.WlInterfaceSpec Interface { get; } = new global::Wayland.WlInterfaceSpec(
            "sample_child",
            1,
            new global::Wayland.WlMessageSpec[]
            {
                new global::Wayland.WlMessageSpec("destroy", "", null),
            },
            global::System.Array.Empty<global::Wayland.WlMessageSpec>(),
            static (handle, display) => new SampleChild(handle, display));

        internal SampleChild(nint handle, global::Wayland.WlDisplay display) : base(handle, display)
        {
        }

        protected override global::Wayland.WlInterfaceSpec Spec => Interface;

        /// <summary>Sends the 'destroy' request.</summary>
        public void Destroy()
        {
            MarshalDestructor(0u, default);
        }

        /// <summary>Routes disposal through the 'destroy' destructor request.</summary>
        protected override void DisposeCore() => Destroy();

        protected override void HandleEvent(uint opcode, global::System.ReadOnlySpan<global::Wayland.WlArg> args)
        {
        }
    }

    /// <summary>Server resource for the 'sample_child' interface.</summary>
    [global::Wayland.WaylandResource("sample_child")]
    public sealed partial class SampleChildResource : global::Wayland.Server.WlResource
    {
        /// <summary>Creates the resource for a bound global or a client-requested object id.</summary>
        public SampleChildResource(global::Wayland.Server.WlClient client, uint version, uint id) : base(client, SampleChild.Interface, version, id)
        {
        }

        protected override global::Wayland.WlInterfaceSpec Spec => SampleChild.Interface;

        /// <summary>Arguments of the 'destroy' event.</summary>
        public readonly struct DestroyRequestEventArgs
        {
        }

        /// <summary>Raised when the client sends the 'destroy' request. The resource is destroyed automatically after this event.</summary>
        public event global::System.EventHandler<DestroyRequestEventArgs>? DestroyRequest;

        protected override void HandleRequest(uint opcode, global::System.ReadOnlySpan<global::Wayland.WlArg> args)
        {
            switch (opcode)
            {
                case 0u:
                    DestroyRequest?.Invoke(this, new DestroyRequestEventArgs());
                    CompleteDestructorRequest();
                    break;
            }
        }
    }

}
