using System;
using System.Collections.Generic;
using System.Linq;

namespace WaylandSharpest.Generator
{
    /// <summary>How an interface name resolves to already-known generated types.</summary>
    internal sealed class InterfaceRef
    {
        public InterfaceRef(string proxyFqn, string? resourceFqn, InterfaceModel? local)
        {
            ProxyFqn = proxyFqn;
            ResourceFqn = resourceFqn;
            Local = local;
        }

        /// <summary>Fully qualified proxy class name, such as <c>global::Wayland.WlSurface</c>.</summary>
        public string ProxyFqn { get; }

        public string? ResourceFqn { get; }

        /// <summary>Set when the interface is defined by XML in the current compilation.</summary>
        public InterfaceModel? Local { get; }
    }

    internal sealed class ProtocolEmitter
    {
        private const string Runtime = "global::Wayland";
        private const string SpecType = Runtime + ".WlInterfaceSpec";
        private const string MessageType = Runtime + ".WlMessageSpec";
        private const string ArgType = Runtime + ".WlArg";
        private const string ArgSpan = "global::System.ReadOnlySpan<" + ArgType + ">";
        private const string ProxyBase = Runtime + ".WlProxy";
        private const string ResourceBase = Runtime + ".Server.WlResource";
        private const string ClientType = Runtime + ".Server.WlClient";
        private const string FixedType = Runtime + ".WlFixed";

        private readonly IReadOnlyDictionary<string, InterfaceRef> _interfaces;
        private readonly Action<string> _reportUnresolved;
        private readonly bool _emitVersionGuards;

        public ProtocolEmitter(
            IReadOnlyDictionary<string, InterfaceRef> interfaces,
            Action<string> reportUnresolved,
            bool emitVersionGuards = true)
        {
            _interfaces = interfaces;
            _reportUnresolved = reportUnresolved;
            _emitVersionGuards = emitVersionGuards;
        }

        public string Emit(ProtocolModel protocol)
        {
            var w = new CodeWriter();
            w.Line("// <auto-generated>");
            w.Line($"// Generated by WaylandSharpest.Generator from protocol '{protocol.Name}'.");
            w.Line("// </auto-generated>");
            w.Line("#nullable enable");
            w.Line();
            w.Open($"namespace {protocol.Namespace}");

            foreach (var iface in protocol.Interfaces)
            {
                EmitProxyClass(w, iface);
                w.Line();
                EmitResourceClass(w, iface);
                w.Line();
            }

            w.Close();
            return w.ToString();
        }

        private InterfaceRef? Resolve(string? interfaceName, string context)
        {
            if (interfaceName is null)
            {
                return null;
            }

            if (_interfaces.TryGetValue(interfaceName, out var found))
            {
                return found;
            }

            _reportUnresolved($"Interface '{interfaceName}' referenced by {context} could not be resolved; falling back to untyped bindings.");
            return null;
        }

        /// <summary>Resolves an enum reference to a fully-qualified C# enum type name.</summary>
        private string? ResolveEnum(ArgModel arg, InterfaceModel currentInterface, string currentClassFqn)
        {
            if (arg.EnumRef is null)
            {
                return null;
            }

            var dot = arg.EnumRef.IndexOf('.');
            if (dot < 0)
            {
                return $"{currentClassFqn}.{NameUtils.Pascal(arg.EnumRef)}";
            }

            var ifaceName = arg.EnumRef.Substring(0, dot);
            var enumName = arg.EnumRef.Substring(dot + 1);
            var target = Resolve(ifaceName, $"enum reference '{arg.EnumRef}'");
            return target is null ? null : $"{target.ProxyFqn}.{NameUtils.Pascal(enumName)}";
        }

        /// <summary>
        /// Emits the <c>Supports*</c> predicate for a message introduced after
        /// version 1 and returns its name, or null when the message is always
        /// available. The name is reserved in <paramref name="used"/> so the
        /// collision handling for member names stays intact.
        /// </summary>
        private static string? EmitVersionPredicate(
            CodeWriter w, InterfaceModel iface, MessageModel message, string memberName, HashSet<string> used)
        {
            if (message.Since <= 1)
            {
                return null;
            }

            var name = AdjustName("Supports" + memberName, used, "_");
            w.Doc($"Whether this object's negotiated version supports '{message.Name}' (since {message.Since}).");
            w.Line($"public bool {name} => Version >= {message.Since}u;");
            w.Line();
            return name;
        }

        /// <summary>Emits the guard that keeps a too-new message off the wire.</summary>
        private void EmitVersionGuard(CodeWriter w, InterfaceModel iface, MessageModel message)
        {
            if (!_emitVersionGuards || message.Since <= 1)
            {
                return;
            }

            w.Open($"if (Version < {message.Since}u)");
            w.Line($"throw new {Runtime}.WaylandVersionException(\"{iface.Name}\", \"{message.Name}\", {message.Since}u, Version);");
            w.Close();
            w.Line();
        }

        /// <summary>Appends the availability note protocol XML carries as <c>since</c>.</summary>
        private static string? WithSince(string? summary, int since)
        {
            if (since <= 1)
            {
                return summary;
            }

            var note = $"Available since version {since}.";
            if (string.IsNullOrWhiteSpace(summary))
            {
                return note;
            }

            // Protocol summaries are sentence fragments without terminators, so
            // the note needs one supplied or the two run together.
            var text = summary!.Trim();
            var terminated = ".?!:".IndexOf(text[text.Length - 1]) >= 0;
            return terminated ? $"{text} {note}" : $"{text}. {note}";
        }

        private static string? EntrySummary(EnumEntryModel entry) => WithSince(entry.Summary, entry.Since);

        /// <summary>Emits <c>[Obsolete]</c> for a message the protocol marks deprecated.</summary>
        private static void EmitDeprecation(CodeWriter w, MessageModel message)
        {
            if (message.DeprecatedSince is { } deprecated)
            {
                w.Line($"[global::System.Obsolete(\"Deprecated since version {deprecated}.\")]");
            }
        }

        private static string AdjustName(string candidate, HashSet<string> used, string suffix)
        {
            var name = candidate;
            while (!used.Add(name))
            {
                name += suffix;
            }

            return name;
        }

        private void EmitProxyClass(CodeWriter w, InterfaceModel iface)
        {
            var cls = NameUtils.Pascal(iface.Name);
            var clsFqn = ClassFqnOf(iface);

            w.Doc(iface.Summary is null ? $"Client proxy for the '{iface.Name}' interface." : $"{iface.Summary} (client proxy for '{iface.Name}').", iface.Description);
            w.Line($"[{Runtime}.WaylandProxy(\"{iface.Name}\")]");
            w.Open($"public sealed partial class {cls} : {ProxyBase}, {Runtime}.IWaylandObject<{cls}>");

            EmitInterfaceSpec(w, iface, cls);
            w.Line();
            w.Line($"internal {cls}(nint handle, {Runtime}.WlDisplay display) : base(handle, display)");
            w.Line("{");
            w.Line("}");
            w.Line();
            w.Line($"protected override {SpecType} Spec => Interface;");

            var used = new HashSet<string>(StringComparer.Ordinal)
            {
                cls, "Interface", "Spec", "Display", "RawHandle", "Id", "Version", "IsDestroyed", "Dispose",
            };

            foreach (var e in iface.Enums)
            {
                w.Line();
                EmitEnum(w, e, used);
            }

            var methodNames = new Dictionary<MessageModel, string>();
            foreach (var request in iface.Requests)
            {
                w.Line();
                methodNames[request] = EmitRequestMethod(w, iface, request, used, clsFqn);
            }

            if (iface.Destructor is { } destructor)
            {
                w.Line();
                if (destructor.Since > 1)
                {
                    // The destructor request itself may post-date the negotiated
                    // version (wl_compositor.release is since 7). Sending it
                    // anyway is a protocol violation, so an older object falls
                    // back to destroying the proxy without notifying the server —
                    // which is what wayland-scanner's separate _destroy is for.
                    w.Doc($"Routes disposal through the '{destructor.Name}' destructor request where the negotiated version has it.");
                    w.Open("protected override void DisposeCore()");
                    w.Open($"if (Version >= {destructor.Since}u)");
                    w.Line($"{methodNames[destructor]}();");
                    w.Close();
                    w.Open("else");
                    w.Line("base.DisposeCore();");
                    w.Close();
                    w.Close();
                }
                else
                {
                    w.Doc($"Routes disposal through the '{destructor.Name}' destructor request.");
                    w.Line($"protected override void DisposeCore() => {methodNames[destructor]}();");
                }
            }

            var eventNames = new Dictionary<MessageModel, string>();
            foreach (var evt in iface.Events)
            {
                w.Line();
                eventNames[evt] = EmitProxyEvent(w, iface, evt, used, clsFqn);
            }

            w.Line();
            EmitProxyDispatch(w, iface, eventNames, clsFqn);
            w.Close();
        }

        private void EmitInterfaceSpec(CodeWriter w, InterfaceModel iface, string cls)
        {
            w.Doc($"Interface metadata for '{iface.Name}' version {iface.Version}.");
            w.Line($"public static {SpecType} Interface {{ get; }} = new {SpecType}(");
            w.Indent();
            w.Line($"\"{iface.Name}\",");
            w.Line($"{iface.Version},");
            EmitMessageSpecArray(w, iface.Requests);
            EmitMessageSpecArray(w, iface.Events);
            w.Line($"static (handle, display) => new {cls}(handle, display));");
            w.Outdent();
        }

        private void EmitMessageSpecArray(CodeWriter w, List<MessageModel> messages)
        {
            if (messages.Count == 0)
            {
                w.Line($"global::System.Array.Empty<{MessageType}>(),");
                return;
            }

            w.Line($"new {MessageType}[]");
            w.Line("{");
            w.Indent();
            foreach (var message in messages)
            {
                var types = message.BuildWireTypes();
                string typesExpr;
                if (types.Count == 0)
                {
                    typesExpr = "null";
                }
                else
                {
                    var entries = types.Select(t =>
                    {
                        if (t is null)
                        {
                            return "null";
                        }

                        var target = Resolve(t, $"'{message.Name}'");
                        // The '!' silences nullable flow analysis for self-referential
                        // specs (a lambda inside the initializer of the property it reads).
                        return target is null ? "null" : $"static () => {target.ProxyFqn}.Interface!";
                    });
                    typesExpr = $"new global::System.Func<{SpecType}>?[] {{ {string.Join(", ", entries)} }}";
                }

                w.Line($"new {MessageType}(\"{message.Name}\", \"{message.BuildSignature()}\", {typesExpr}),");
            }

            w.Outdent();
            w.Line("},");
        }

        private void EmitEnum(CodeWriter w, EnumModel e, HashSet<string> used)
        {
            var name = AdjustName(NameUtils.Pascal(e.Name), used, "Enum");
            var backing = e.NeedsUnsignedBacking ? "uint" : "int";
            w.Doc(e.Summary, e.Description);
            if (e.IsBitfield)
            {
                w.Line("[global::System.Flags]");
            }

            w.Open($"public enum {name} : {backing}");
            var memberNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var entry in e.Entries)
            {
                var memberName = AdjustName(NameUtils.Pascal(entry.Name), memberNames, "_");
                w.Doc(EntrySummary(entry), entry.Description);
                var literal = e.NeedsUnsignedBacking ? $"{(uint)entry.Value}u" : entry.Value.ToString();
                w.Line($"{memberName} = {literal},");
            }

            w.Close();
        }

        private sealed class ArgPlan
        {
            public readonly List<string> Params = new List<string>();
            public readonly List<string> Allocations = new List<string>();
            public readonly List<string> Assignments = new List<string>();
            public readonly List<string> Cleanups = new List<string>();
            public int WireCount;
            public string? ReturnType;
            public string? ConstructorIfaceExpr;
            public bool IsBindStyle;
            public string? GenericBindName;
        }

        /// <summary>Emits a client request method; returns the chosen method name.</summary>
        private string EmitRequestMethod(CodeWriter w, InterfaceModel iface, MessageModel request, HashSet<string> used, string clsFqn)
        {
            var methodName = AdjustName(NameUtils.Pascal(request.Name), used, "_");
            var plan = BuildClientArgPlan(iface, request, clsFqn, forProxy: true);

            var doc = WithSince(request.Summary ?? $"Sends the '{request.Name}' request.", request.Since);

            EmitVersionPredicate(w, iface, request, methodName, used);

            w.Doc(doc, request.Description);
            EmitDeprecation(w, request);
            var returnType = plan.ReturnType ?? "void";
            w.Open($"public {returnType} {methodName}({string.Join(", ", plan.Params)})");
            EmitVersionGuard(w, iface, request);
            EmitMarshalBody(w, request, plan);
            w.Close();

            if (plan.IsBindStyle)
            {
                w.Line();
                w.Line($"/// <summary>Typed overload of <see cref=\"{methodName}(uint, {SpecType}, uint)\"/> using the interface metadata of <typeparamref name=\"T\"/>.</summary>");
                var forwardedParams = plan.Params
                    .Where(p => !p.StartsWith(SpecType, StringComparison.Ordinal))
                    .Select(p => p.Split(' ').Last())
                    .ToList();
                var declaredParams = plan.Params.Where(p => !p.StartsWith(SpecType, StringComparison.Ordinal)).ToList();
                var forwardArgs = string.Join(", ", forwardedParams.Select(p => p == "version" ? "T.Interface, version" : p));
                w.Line($"public T {methodName}<T>({string.Join(", ", declaredParams)}) where T : {ProxyBase}, {Runtime}.IWaylandObject<T> =>");
                w.Line($"    (T){methodName}({forwardArgs});");
            }

            return methodName;
        }

        private void EmitMarshalBody(CodeWriter w, MessageModel request, ArgPlan plan)
        {
            if (plan.WireCount == 0)
            {
                w.Line(EmitMarshalCall(request, plan, "default"));
                return;
            }

            w.Line($"global::System.Span<{ArgType}> _args = stackalloc {ArgType}[{plan.WireCount}];");
            foreach (var alloc in plan.Allocations)
            {
                w.Line(alloc);
            }

            var hasCleanup = plan.Cleanups.Count > 0;
            if (hasCleanup)
            {
                w.Open("try");
            }

            foreach (var assign in plan.Assignments)
            {
                w.Line(assign);
            }

            w.Line(EmitMarshalCall(request, plan, "_args"));

            if (hasCleanup)
            {
                w.Close();
                w.Open("finally");
                foreach (var cleanup in plan.Cleanups)
                {
                    w.Line(cleanup);
                }

                w.Close();
            }
        }

        private static string EmitMarshalCall(MessageModel request, ArgPlan plan, string argsExpr)
        {
            var opcode = $"{request.Opcode}u";
            if (plan.IsBindStyle)
            {
                return $"return ({plan.ReturnType})MarshalBind({opcode}, {argsExpr}, {plan.GenericBindName}, version);";
            }

            if (plan.ConstructorIfaceExpr is not null)
            {
                // A destructor request may still carry a new_id; the wire call
                // creates the object and destroys the sender in one go.
                var call = request.IsDestructor ? "MarshalDestructorConstructor" : "MarshalConstructor";
                return $"return ({plan.ReturnType}){call}({opcode}, {argsExpr}, {plan.ConstructorIfaceExpr});";
            }

            if (request.IsDestructor)
            {
                return $"MarshalDestructor({opcode}, {argsExpr});";
            }

            return $"MarshalRequest({opcode}, {argsExpr});";
        }

        /// <summary>Builds parameter list and wire-argument marshalling steps for a request (proxy) or event (resource).</summary>
        private ArgPlan BuildClientArgPlan(InterfaceModel iface, MessageModel message, string clsFqn, bool forProxy)
        {
            var plan = new ArgPlan();
            var wire = 0;
            foreach (var arg in message.Args)
            {
                var param = NameUtils.Param(arg.Name);
                var context = $"'{iface.Name}.{message.Name}'";
                switch (arg.Type)
                {
                    case WlArgType.Int:
                    case WlArgType.Uint:
                    {
                        var field = arg.Type == WlArgType.Int ? "I" : "U";
                        var raw = arg.Type == WlArgType.Int ? "int" : "uint";
                        var enumFqn = ResolveEnum(arg, iface, clsFqn);
                        plan.Params.Add($"{enumFqn ?? raw} {param}");
                        var value = enumFqn is null ? param : $"({raw}){param}";
                        plan.Assignments.Add($"_args[{wire}].{field} = {value};");
                        wire++;
                        break;
                    }

                    case WlArgType.Fixed:
                        plan.Params.Add($"{FixedType} {param}");
                        plan.Assignments.Add($"_args[{wire}].F = {param};");
                        wire++;
                        break;

                    case WlArgType.String:
                        plan.Params.Add($"string{(arg.AllowNull ? "?" : "")} {param}");
                        plan.Allocations.Add($"nint _s{wire} = AllocString({param});");
                        plan.Assignments.Add($"_args[{wire}].Ptr = _s{wire};");
                        plan.Cleanups.Add($"FreeString(_s{wire});");
                        wire++;
                        break;

                    case WlArgType.Object:
                    {
                        var target = Resolve(arg.Interface, context);
                        var typeName = forProxy
                            ? target?.ProxyFqn ?? ProxyBase
                            : target?.ResourceFqn ?? ResourceBase;
                        plan.Params.Add($"{typeName}{(arg.AllowNull ? "?" : "")} {param}");
                        plan.Assignments.Add(arg.AllowNull
                            ? $"_args[{wire}].Ptr = {param} is null ? 0 : {param}.RawHandle;"
                            : $"_args[{wire}].Ptr = {param}.RawHandle;");
                        wire++;
                        break;
                    }

                    case WlArgType.NewId when arg.Interface is null:
                        // wl_registry.bind style: interface name and version travel explicitly.
                        plan.Params.Add($"{SpecType} iface");
                        plan.Params.Add("uint version");
                        plan.Allocations.Add($"nint _s{wire} = AllocString(iface.Name);");
                        plan.Assignments.Add($"_args[{wire}].Ptr = _s{wire};");
                        plan.Assignments.Add($"_args[{wire + 1}].U = version;");
                        plan.Cleanups.Add($"FreeString(_s{wire});");
                        plan.IsBindStyle = true;
                        plan.GenericBindName = "iface";
                        plan.ReturnType = ProxyBase;
                        wire += 3;
                        break;

                    case WlArgType.NewId:
                    {
                        var target = Resolve(arg.Interface, context);
                        if (forProxy)
                        {
                            plan.ReturnType = target?.ProxyFqn ?? ProxyBase;
                            plan.ConstructorIfaceExpr = target is null
                                ? throw new ProtocolParseException($"Request {context} creates unresolved interface '{arg.Interface}'.")
                                : $"{target.ProxyFqn}.Interface";
                        }
                        else
                        {
                            // Server-side event with a new_id argument carries the
                            // resource created by the compositor.
                            var typeName = target?.ResourceFqn ?? ResourceBase;
                            plan.Params.Add($"{typeName} {param}");
                            plan.Assignments.Add($"_args[{wire}].Ptr = {param}.RawHandle;");
                        }

                        wire++;
                        break;
                    }

                    case WlArgType.Array:
                        plan.Params.Add($"global::System.ReadOnlySpan<byte> {param}");
                        plan.Allocations.Add($"var _a{wire} = AllocArray({param});");
                        plan.Assignments.Add($"_args[{wire}].Ptr = _a{wire}.Pointer;");
                        plan.Cleanups.Add($"_a{wire}.Dispose();");
                        wire++;
                        break;

                    case WlArgType.Fd:
                        plan.Params.Add($"int {param}");
                        plan.Assignments.Add($"_args[{wire}].Fd = {param};");
                        wire++;
                        break;
                }
            }

            plan.WireCount = wire;
            return plan;
        }

        private sealed class EventPlan
        {
            public readonly List<string> Props = new List<string>();
            public readonly List<string> CtorParams = new List<string>();
            public readonly List<string> CtorAssignments = new List<string>();
            public readonly List<string> DecodeExprs = new List<string>();
        }

        private string EmitProxyEvent(CodeWriter w, InterfaceModel iface, MessageModel evt, HashSet<string> used, string clsFqn)
        {
            var evtName = AdjustName(NameUtils.Pascal(evt.Name), used, "Event");
            var argsStruct = evtName + "EventArgs";
            var plan = BuildEventPlan(iface, evt, clsFqn, forProxy: true);

            EmitEventArgsStruct(w, argsStruct, evt, plan);
            w.Line();
            var doc = WithSince(evt.Summary ?? $"Raised for the '{evt.Name}' event.", evt.Since);

            w.Doc(doc, evt.Description);
            EmitDeprecation(w, evt);
            w.Line($"public event global::System.EventHandler<{argsStruct}>? {evtName};");
            return evtName;
        }

        private static void EmitEventArgsStruct(CodeWriter w, string argsStruct, MessageModel evt, EventPlan plan)
        {
            w.Doc($"Arguments of the '{evt.Name}' event.");
            w.Open($"public readonly struct {argsStruct}");
            if (plan.CtorParams.Count > 0)
            {
                w.Open($"internal {argsStruct}({string.Join(", ", plan.CtorParams)})");
                foreach (var assign in plan.CtorAssignments)
                {
                    w.Line(assign);
                }

                w.Close();
                w.Line();
            }

            foreach (var prop in plan.Props)
            {
                w.Line(prop);
            }

            w.Close();
        }

        /// <summary>Builds EventArgs members and decode expressions for a proxy event or resource request.</summary>
        private EventPlan BuildEventPlan(InterfaceModel iface, MessageModel message, string clsFqn, bool forProxy)
        {
            var plan = new EventPlan();
            var wire = 0;
            void Add(string type, string argName, string decode, string? summary)
            {
                var prop = NameUtils.Pascal(argName);
                var param = NameUtils.Param(argName);
                plan.CtorParams.Add($"{type} {param}");
                plan.CtorAssignments.Add($"{prop} = {param};");
                if (!string.IsNullOrWhiteSpace(summary))
                {
                    plan.Props.Add($"/// <summary>{NameUtils.EscapeXmlDoc(summary!.Trim())}</summary>");
                }

                plan.Props.Add($"public {type} {prop} {{ get; }}");
                plan.DecodeExprs.Add(decode);
            }

            foreach (var arg in message.Args)
            {
                var context = $"'{iface.Name}.{message.Name}'";
                switch (arg.Type)
                {
                    case WlArgType.Int:
                    case WlArgType.Uint:
                    {
                        var field = arg.Type == WlArgType.Int ? "I" : "U";
                        var raw = arg.Type == WlArgType.Int ? "int" : "uint";
                        var enumFqn = ResolveEnum(arg, iface, clsFqn);
                        var decode = enumFqn is null ? $"args[{wire}].{field}" : $"({enumFqn})args[{wire}].{field}";
                        Add(enumFqn ?? raw, arg.Name, decode, arg.Summary);
                        wire++;
                        break;
                    }

                    case WlArgType.Fixed:
                        Add(FixedType, arg.Name, $"args[{wire}].F", arg.Summary);
                        wire++;
                        break;

                    case WlArgType.String:
                        Add(
                            arg.AllowNull ? "string?" : "string",
                            arg.Name,
                            arg.AllowNull ? $"GetString(args[{wire}])" : $"GetString(args[{wire}])!",
                            arg.Summary);
                        wire++;
                        break;

                    case WlArgType.Object:
                    {
                        var target = Resolve(arg.Interface, context);
                        if (forProxy)
                        {
                            var type = target?.ProxyFqn ?? ProxyBase;
                            Add($"{type}?", arg.Name, $"GetProxy<{type}>(args[{wire}])", arg.Summary);
                            Add(
                                "nint",
                                arg.Name + "_handle",
                                $"GetProxyHandle(args[{wire}])",
                                $"Raw wl_proxy pointer of '{arg.Name}'; valid even when the proxy is owned by another library.");
                        }
                        else
                        {
                            var type = target?.ResourceFqn ?? ResourceBase;
                            Add($"{type}?", arg.Name, $"GetResource<{type}>(args[{wire}])", arg.Summary);
                            Add(
                                "nint",
                                arg.Name + "_handle",
                                $"GetResourceHandle(args[{wire}])",
                                $"Raw wl_resource pointer of '{arg.Name}'; valid even when the resource is owned by another library.");
                        }

                        wire++;
                        break;
                    }

                    case WlArgType.NewId when arg.Interface is null:
                        // Untyped new_id (registry bind pattern) expands to
                        // interface-name string, version, and the new object id.
                        Add("string", arg.Name + "_interface", $"GetString(args[{wire}])!", "Requested interface name.");
                        Add("uint", arg.Name + "_version", $"args[{wire + 1}].U", "Requested interface version.");
                        Add("uint", arg.Name, $"args[{wire + 2}].U", "New object id; construct the matching resource with it.");
                        wire += 3;
                        break;

                    case WlArgType.NewId:
                    {
                        var target = Resolve(arg.Interface, context);
                        if (forProxy)
                        {
                            if (target is null)
                            {
                                Add("nint", arg.Name, $"args[{wire}].Ptr", "Raw proxy pointer (interface was unresolved).");
                            }
                            else
                            {
                                Add(target.ProxyFqn, arg.Name, $"({target.ProxyFqn})WrapNewProxy(args[{wire}], {target.ProxyFqn}.Interface)", arg.Summary);
                            }
                        }
                        else
                        {
                            // Client-allocated id of the object this request creates.
                            Add("uint", arg.Name, $"args[{wire}].U", arg.Summary ?? "New object id; construct the matching resource with it.");
                        }

                        wire++;
                        break;
                    }

                    case WlArgType.Array:
                        Add("byte[]", arg.Name, $"GetArray(args[{wire}])", arg.Summary);
                        wire++;
                        break;

                    case WlArgType.Fd:
                        Add("int", arg.Name, $"args[{wire}].Fd", arg.Summary);
                        wire++;
                        break;
                }
            }

            return plan;
        }

        /// <summary>
        /// Suppresses the obsolete-member warning around generated dispatch: the
        /// switch has to raise the event for a deprecated message like any
        /// other, and consumers build with warnings as errors.
        /// </summary>
        private static void OpenDeprecationSuppression(CodeWriter w, IEnumerable<MessageModel> messages)
        {
            if (messages.Any(m => m.DeprecatedSince is not null))
            {
                w.Line("#pragma warning disable CS0618");
            }
        }

        private static void CloseDeprecationSuppression(CodeWriter w, IEnumerable<MessageModel> messages)
        {
            if (messages.Any(m => m.DeprecatedSince is not null))
            {
                w.Line("#pragma warning restore CS0618");
            }
        }

        private void EmitProxyDispatch(CodeWriter w, InterfaceModel iface, Dictionary<MessageModel, string> eventNames, string clsFqn)
        {
            OpenDeprecationSuppression(w, iface.Events);
            w.Open($"protected override void HandleEvent(uint opcode, {ArgSpan} args)");
            if (iface.Events.Count == 0)
            {
                w.Close();
                CloseDeprecationSuppression(w, iface.Events);
                return;
            }

            w.Open("switch (opcode)");
            foreach (var evt in iface.Events)
            {
                var evtName = eventNames[evt];
                var plan = BuildEventPlan(iface, evt, clsFqn, forProxy: true);
                w.Line($"case {evt.Opcode}u:");
                var invokeArgs = string.Join(", ", plan.DecodeExprs);
                w.Line($"    {evtName}?.Invoke(this, new {evtName}EventArgs({invokeArgs}));");
                w.Line("    break;");
            }

            w.Close();
            w.Close();
            CloseDeprecationSuppression(w, iface.Events);
        }

        private void EmitResourceClass(CodeWriter w, InterfaceModel iface)
        {
            var proxyCls = NameUtils.Pascal(iface.Name);
            var cls = proxyCls + "Resource";

            w.Doc(iface.Summary is null ? $"Server resource for the '{iface.Name}' interface." : $"{iface.Summary} (server resource for '{iface.Name}').", iface.Description);
            w.Line($"[{Runtime}.WaylandResource(\"{iface.Name}\")]");
            w.Open($"public sealed partial class {cls} : {ResourceBase}");

            w.Doc("Creates the resource for a bound global or a client-requested object id.");
            w.Line($"public {cls}({ClientType} client, uint version, uint id) : base(client, {proxyCls}.Interface, version, id)");
            w.Line("{");
            w.Line("}");
            w.Line();
            w.Line($"protected override {SpecType} Spec => {proxyCls}.Interface;");

            var used = new HashSet<string>(StringComparer.Ordinal)
            {
                cls, "Spec", "Client", "RawHandle", "Id", "Version", "IsDestroyed", "Destroyed", "Destroy", "PostError",
            };

            var clsFqn = ClassFqnOf(iface);

            // Client requests become C# events.
            var requestNames = new Dictionary<MessageModel, string>();
            foreach (var request in iface.Requests)
            {
                w.Line();
                var evtName = AdjustName(NameUtils.Pascal(request.Name), used, "Request");
                requestNames[request] = evtName;
                var plan = BuildEventPlan(iface, request, clsFqn, forProxy: false);
                EmitEventArgsStruct(w, evtName + "EventArgs", request, plan);
                w.Line();
                var doc = WithSince(request.Summary ?? $"Raised when the client sends the '{request.Name}' request.", request.Since);
                if (request.IsDestructor)
                {
                    doc += " The resource is destroyed automatically after this event.";
                }

                w.Doc(doc, request.Description);
                EmitDeprecation(w, request);
                w.Line($"public event global::System.EventHandler<{evtName}EventArgs>? {evtName};");
            }

            // Server events become Send* methods.
            foreach (var evt in iface.Events)
            {
                w.Line();
                var methodName = AdjustName("Send" + NameUtils.Pascal(evt.Name), used, "_");
                var plan = BuildClientArgPlan(iface, evt, clsFqn, forProxy: false);
                var doc = WithSince(evt.Summary ?? $"Sends the '{evt.Name}' event to the client.", evt.Since);

                EmitVersionPredicate(w, iface, evt, methodName, used);

                w.Doc(doc, evt.Description);
                EmitDeprecation(w, evt);
                w.Open($"public void {methodName}({string.Join(", ", plan.Params)})");
                EmitVersionGuard(w, iface, evt);
                EmitPostBody(w, evt, plan);
                w.Close();
            }

            w.Line();
            OpenDeprecationSuppression(w, iface.Requests);
            w.Open($"protected override void HandleRequest(uint opcode, {ArgSpan} args)");
            if (iface.Requests.Count > 0)
            {
                w.Open("switch (opcode)");
                foreach (var request in iface.Requests)
                {
                    var evtName = requestNames[request];
                    var plan = BuildEventPlan(iface, request, clsFqn, forProxy: false);
                    w.Line($"case {request.Opcode}u:");
                    var invokeArgs = string.Join(", ", plan.DecodeExprs);
                    w.Line($"    {evtName}?.Invoke(this, new {evtName}EventArgs({invokeArgs}));");
                    if (request.IsDestructor)
                    {
                        w.Line("    CompleteDestructorRequest();");
                    }

                    w.Line("    break;");
                }

                w.Close();
            }

            w.Close();
            CloseDeprecationSuppression(w, iface.Requests);
            w.Close();
        }

        private void EmitPostBody(CodeWriter w, MessageModel evt, ArgPlan plan)
        {
            if (plan.WireCount == 0)
            {
                w.Line($"PostEvent({evt.Opcode}u, default);");
                return;
            }

            w.Line($"global::System.Span<{ArgType}> _args = stackalloc {ArgType}[{plan.WireCount}];");
            foreach (var alloc in plan.Allocations)
            {
                w.Line(alloc);
            }

            var hasCleanup = plan.Cleanups.Count > 0;
            if (hasCleanup)
            {
                w.Open("try");
            }

            foreach (var assign in plan.Assignments)
            {
                w.Line(assign);
            }

            w.Line($"PostEvent({evt.Opcode}u, _args);");

            if (hasCleanup)
            {
                w.Close();
                w.Open("finally");
                foreach (var cleanup in plan.Cleanups)
                {
                    w.Line(cleanup);
                }

                w.Close();
            }
        }

        private string ClassFqnOf(InterfaceModel iface) =>
            _interfaces.TryGetValue(iface.Name, out var self)
                ? self.ProxyFqn
                : "global::" + NameUtils.Pascal(iface.Name);
    }
}
